# Generated by Django 5.2 on 2025-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasme', '0003_remove_profileuser_profile_friendship_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='song_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
