# Generated by Django 5.2 on 2025-04-15 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasme', '0004_track_song_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listenparty',
            name='que',
        ),
        migrations.AddField(
            model_name='listenparty',
            name='mobile_lp_users',
            field=models.ManyToManyField(blank=True, related_name='mobile_lp_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
